# Generated by Django 2.2.1 on 2020-09-25 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalleproducto',
            options={},
        ),
        migrations.AlterModelTable(
            name='detalleproducto',
            table=None,
        ),
    ]
