# Generated by Django 2.2.1 on 2020-09-25 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_auto_20200924_2359'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalleproducto',
            options={'verbose_name': 'Detalle producto', 'verbose_name_plural': 'Detalle de productos'},
        ),
        migrations.AlterModelTable(
            name='detalleproducto',
            table='detalleproducto',
        ),
    ]
